DROP TABLE IF EXISTS `UsuarioAccesos`;


CREATE TABLE UsuarioAccesos
(
	Id				INTEGER AUTO_INCREMENT,
	IdUsuario     	INTEGER NOT NULL,
	IdAcceso     	INTEGER NOT NULL,
	
	PRIMARY KEY (Id)
) AUTO_INCREMENT = 1;